version: '3.7'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/backend/app
    ports:
      - 8004:8004
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: fastapi
    command: [
      "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"
    ]

  db:
    image: postgres:15-alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - type: bind
        source: ./backend/postgres-db
        target: /var/lib/postgresql/data
    container_name: postgres

  # nuxt-dev:
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile
  #   # image: node:20.5.1
  #   image: node:16.18.0-alpine
  #   working_dir: /frontend
  #   volumes:
  #     - ./frontend:/frontend
  #   expose:
  #     - 3000
  #     - 24678
  #   ports:
  #     - 3000:3000
  #     - 24678:24678
  #   environment:
  #     - NUXT_PORT=3000
  #   container_name: nuxt-dev
  #   command: sh -c "npm install && npm run dev"

  # nginx:
  #   image: nginx:stable-alpine3.17
  #   volumes:
  #     - ./nginx:/etc/nginx
  #     - ./frontend:/frontend
  #   ports:
  #     - 80:80
  #   env_file:
  #     - .env
  #   environment:
  #     - NGINX_HOST=${NGINX_HOST}
  #     - NGINX_PORT=80
  #   depends_on:
  #     - nuxt-dev
  #   container_name: nginx