version: '3.7'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/backend/app
    ports:
      - 8004:8004
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: fastapi

  db:
    image: postgres:15-alpine3.17
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - type: bind
        source: ./backend/postgres-db
        target: /var/lib/postgresql/data
    container_name: postgres


  nuxt_dev:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
    - ./frontend:/frontend
    - /frontend/node_modules
    ports:
      - "80:3000"
      - "24678:24678"







  # nuxt:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/frontend
  #   ports:
  #     - 3000:3000
  #   container_name: nuxt

  # nginx:
  #   image: nginx:stable-alpine3.17
  #   volumes:
  #     - ./nginx:/etc/nginx
  #     - ./frontend:/frontend
  #   ports:
  #     - 80:80
  #   env_file:
  #     - .env
  #   environment:
  #     - NGINX_HOST=${NGINX_HOST}
  #     - NGINX_PORT=80
  #   depends_on:
  #     - nuxt
  #   container_name: nginx
